#pragma once
#include <memory>
#include <vector>
#include <iostream>
#include "telemetry.pb.h" // Generated by gRPC/Protobuf

namespace mime {
namespace edge {

// Abstract interface for any hardware implementation.
// This allows us to easily swap between Real hardware and Mock hardware.
class HardwareInterface {
public:
    virtual ~HardwareInterface() = default;
    
    // Initialize the hardware connection (e.g., open serial port, connect to camera)
    virtual bool initialize() = 0;
    
    // Poll the latest data from the hardware sensors
    virtual mime::telemetry::EdgeTelemetry read_telemetry() = 0;
};

// Mock implementation for testing without real hardware attached
class MockHardware : public HardwareInterface {
private:
    uint64_t counter = 0;
public:
    bool initialize() override {
        std::cout << "MockHardware initialized successfully." << std::endl;
        return true;
    }

    mime::telemetry::EdgeTelemetry read_telemetry() override {
        mime::telemetry::EdgeTelemetry telemetry;
        // Simulate 10ms steps for 100Hz frequency
        telemetry.set_timestamp_ns(counter * 10000000); 
        
        // Mock IMU data (wrist orientation)
        auto* imu = telemetry.add_imu_array();
        imu->set_sensor_id("wrist_imu_01");
        auto* q = imu->mutable_orientation();
        q->set_w(1.0); q->set_x(0.0); q->set_y(0.0); q->set_z(0.0);
        
        // Mock optical data from camera
        auto* pos = telemetry.mutable_optical_tracking_position();
        pos->set_x(0.5); pos->set_y(0.2); pos->set_z(1.0);
        
        // Mock flex sensors (sine wave for testing gripper motion)
        auto* flex = telemetry.mutable_flex_sensors();
        // In a real scenario, this would read ADC values from the flex sensors
        flex->set_thumb(0.5);
        flex->set_index(0.5);
        
        counter++;
        return telemetry;
    }
};

} // namespace edge
} // namespace mime
