# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MimeTelemetryServiceStub:
    """The core communication interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_unary(
                '/mime.telemetry.MimeTelemetryService/StreamTelemetry',
                request_serializer=telemetry__pb2.EdgeTelemetry.SerializeToString,
                response_deserializer=telemetry__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.SubscribeFusedState = channel.unary_stream(
                '/mime.telemetry.MimeTelemetryService/SubscribeFusedState',
                request_serializer=telemetry__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=telemetry__pb2.FusedState.FromString,
                _registered_method=True)


class MimeTelemetryServiceServicer:
    """The core communication interface
    """

    def StreamTelemetry(self, request_iterator, context):
        """A client-side streaming RPC for high-frequency data from the Edge Node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeFusedState(self, request, context):
        """A server-side streaming RPC for the Visualizer to subscribe to the math engine
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MimeTelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=telemetry__pb2.EdgeTelemetry.FromString,
                    response_serializer=telemetry__pb2.StreamResponse.SerializeToString,
            ),
            'SubscribeFusedState': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeFusedState,
                    request_deserializer=telemetry__pb2.SubscribeRequest.FromString,
                    response_serializer=telemetry__pb2.FusedState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mime.telemetry.MimeTelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mime.telemetry.MimeTelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MimeTelemetryService:
    """The core communication interface
    """

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/mime.telemetry.MimeTelemetryService/StreamTelemetry',
            telemetry__pb2.EdgeTelemetry.SerializeToString,
            telemetry__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeFusedState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mime.telemetry.MimeTelemetryService/SubscribeFusedState',
            telemetry__pb2.SubscribeRequest.SerializeToString,
            telemetry__pb2.FusedState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
