# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x0emime.telemetry\"*\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"8\n\nQuaternion\x12\t\n\x01w\x18\x01 \x01(\x01\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\"\x86\x01\n\nIMUReading\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12/\n\x0borientation\x18\x02 \x01(\x0b\x32\x1a.mime.telemetry.Quaternion\x12\x34\n\x13linear_acceleration\x18\x03 \x01(\x0b\x32\x17.mime.telemetry.Point3D\"+\n\x0b\x46lexSensors\x12\r\n\x05thumb\x18\x01 \x01(\x01\x12\r\n\x05index\x18\x02 \x01(\x01\"\xc3\x01\n\rEdgeTelemetry\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x04\x12-\n\timu_array\x18\x02 \x03(\x0b\x32\x1a.mime.telemetry.IMUReading\x12:\n\x19optical_tracking_position\x18\x03 \x01(\x0b\x32\x17.mime.telemetry.Point3D\x12\x31\n\x0c\x66lex_sensors\x18\x04 \x01(\x0b\x32\x1b.mime.telemetry.FlexSensors\"!\n\x0eStreamResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x12\n\x10SubscribeRequest\"\xb8\x01\n\nFusedState\x12\n\n\x02px\x18\x01 \x01(\x01\x12\n\n\x02py\x18\x02 \x01(\x01\x12\n\n\x02pz\x18\x03 \x01(\x01\x12\n\n\x02vx\x18\x04 \x01(\x01\x12\n\n\x02vy\x18\x05 \x01(\x01\x12\n\n\x02vz\x18\x06 \x01(\x01\x12/\n\x0borientation\x18\x07 \x01(\x0b\x32\x1a.mime.telemetry.Quaternion\x12\x31\n\x0c\x66lex_sensors\x18\x08 \x01(\x0b\x32\x1b.mime.telemetry.FlexSensors2\xc1\x01\n\x14MimeTelemetryService\x12R\n\x0fStreamTelemetry\x12\x1d.mime.telemetry.EdgeTelemetry\x1a\x1e.mime.telemetry.StreamResponse(\x01\x12U\n\x13SubscribeFusedState\x12 .mime.telemetry.SubscribeRequest\x1a\x1a.mime.telemetry.FusedState0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT3D']._serialized_start=35
  _globals['_POINT3D']._serialized_end=77
  _globals['_QUATERNION']._serialized_start=79
  _globals['_QUATERNION']._serialized_end=135
  _globals['_IMUREADING']._serialized_start=138
  _globals['_IMUREADING']._serialized_end=272
  _globals['_FLEXSENSORS']._serialized_start=274
  _globals['_FLEXSENSORS']._serialized_end=317
  _globals['_EDGETELEMETRY']._serialized_start=320
  _globals['_EDGETELEMETRY']._serialized_end=515
  _globals['_STREAMRESPONSE']._serialized_start=517
  _globals['_STREAMRESPONSE']._serialized_end=550
  _globals['_SUBSCRIBEREQUEST']._serialized_start=552
  _globals['_SUBSCRIBEREQUEST']._serialized_end=570
  _globals['_FUSEDSTATE']._serialized_start=573
  _globals['_FUSEDSTATE']._serialized_end=757
  _globals['_MIMETELEMETRYSERVICE']._serialized_start=760
  _globals['_MIMETELEMETRYSERVICE']._serialized_end=953
# @@protoc_insertion_point(module_scope)
